name: did_app
description:  Manage your European digital identity securely. EUDI Wallet and eIDAS 2.0 compliant, store your documents (ID card, driver's license) and share only necessary information thanks to the SSI philosophy. Full control, privacy guaranteed. Your identity, your rules.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  # Archethic dApp Framework - Contains common components and utilities for Archethic dApps
  archethic_dapp_framework_flutter: ^3.4.3
  
  # Archethic Wallet Client - Used to communicate with the Archethic wallet
  archethic_wallet_client: ^2.1.10

  # Flutter framework
  crypto: ^3.0.6

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1

  freezed_annotation: ^2.4.1

  # Dependency injection
  get_it: ^7.7.0

  # Navigation
  go_router: ^14.6.2

  json_annotation: ^4.8.1

  phone_numbers_parser: ^9.0.3

  # Using Official Material Symbols Icons variable fonts
  material_symbols_icons: ^4.2719.1
  
  # QR Code generation
  qr_flutter: ^4.1.0

  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1
  
  # Biometric authentication
  local_auth: ^2.3.0
  
  # Secure storage for authentication tokens and keys
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  build_runner: ^2.4.15
  daunused: ^1.6.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    
  # Add fonts if needed
  # fonts:
  #   - family: PPTelegraf
  #     fonts:
  #       - asset: assets/fonts/PPTelegraf-Regular.otf
  #         weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
